version: '2'

services:
  minio:
    image: minio/minio:latest
    hostname: minio
    volumes: 
      -  ../../datasets:/data 
    command: server /data --console-address ":9001"
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: SU2orange!

  spark:
    image: docker.io/bitnami/spark:3    
    hostname: spark 
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    links:
      - minio 
  spark-worker:
    image: docker.io/bitnami/spark:3    
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    links:
      - minio 
  jupyter:
#    image: jupyter/pyspark-notebook:latest
    build: ./jupyter
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes       
    ports:
      - "8888:8888"
    volumes: 
      - ./work:/home/jovyan/work
      - ../../datasets:/home/jovyan/datasets