version: '3'
services:
 
  ###############################
  cassandra0:
    image: cassandra:3.11.11
    container_name: cassandra0
    hostname: cassandra0
    ports:
    - 9042:9042
    - 9160:9160
    - 7199:7199
    - 8778:8778
    environment:
    - CASSANDRA_START_RPC=true
    environment:
    - CASSANDRA_SEEDS=cassandra0
    - CASSANDRA_CLUSTER_NAME=mtech_cluster
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
  
  ###############################
  cassandra1:
    image: cassandra:3.11.11
    container_name: cassandra1
    ports:
    - 9142:9042
    command: bash -c 'sleep 60;  /docker-entrypoint.sh cassandra -f'
    depends_on:
      - cassandra0
    links:
      - cassandra0
    environment:
    - CASSANDRA_SEEDS=cassandra0
    - CASSANDRA_CLUSTER_NAME=mtech_cluster
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
  
  ###############################
  cassandra2:
    image: cassandra:3.11.11
    container_name: cassandra2
    ports:
    - 9242:9042
    command: bash -c 'sleep 120;  /docker-entrypoint.sh cassandra -f'
    depends_on:
      - cassandra0
    links:
      - cassandra0
    environment:
    - CASSANDRA_SEEDS=cassandra0
    - CASSANDRA_CLUSTER_NAME=mtech_cluster
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
  

  #############################
  cassandra-web:
#    image: basraven/cassandra-web:latest
    build: ./cassandra-web
    environment:
      HOST_PORT: ":3000"
      CASSANDRA_HOST: cassandra0
      CASSANDRA_PORT: 9042
#      CASSANDRA_USERNAME: username
#      CASSANDRA_PASSWORD: password
    restart: on-failure:10
    ports:
      - "8080:3000"
    depends_on: 
      - cassandra0
      - cassandra1
      - cassandra2
    links: 
      - cassandra0

  drill:
    image: apache/drill:1.19.0
    hostname: drill
    command: /bin/bash
    tty: true
    ports:
    - "8047:8047"
    depends_on:
    - cassandra0
    links:
    - cassandra0

